name = "yanzxd"
compatibility_date = "2026-09-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "MAILBOX_STORE"
id = "ed8d435120ce4931a364ffed852c6cb4"
preview_id = "9aead75645c94a43a57abf0895632068"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "d0f29c72b09a43e4818d425a46ca1f9e"
preview_id = "4d906e5aec2741aa833f5481ea160a07"

[vars]
MAIL_PROVIDER = "webhook"
CUSTOM_DOMAINS = "yaoi.web.id"
APP_NAME = "YanzXD Temp"
APP_URL = "https://yaoi.web.id"
MAILBOX_LIFETIME_MINUTES = "60"
MAX_REQUESTS_PER_MINUTE = "120"
CORS_ALLOWED_ORIGINS = "*"
